<a href="https://colab.research.google.com/github/jasmineyh/data_science_w1/blob/main/Tutorial3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [6]:
b = np.random.rand(3,4)
print(b)


[[0.05164085 0.17297438 0.98626435 0.32774111]
 [0.94656635 0.8494738  0.71909731 0.92263854]
 [0.99745989 0.79269502 0.9971597  0.98785534]]


In [9]:
c=np.ones((3,3))
print(c)
print("")
d=np.zeros((3,4))
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
ori_array=np.random.rand(6,3)
print(ori_array)
print(" ")
transposed_array=ori_array.T
print(transposed_array)

[[0.7227996  0.75426353 0.07820986]
 [0.38669463 0.89765399 0.14799759]
 [0.77295412 0.58524423 0.33675171]
 [0.37357307 0.48094028 0.59167544]
 [0.11268592 0.23839802 0.56782895]
 [0.08268697 0.35463724 0.3208946 ]]
 
[[0.7227996  0.38669463 0.77295412 0.37357307 0.11268592 0.08268697]
 [0.75426353 0.89765399 0.58524423 0.48094028 0.23839802 0.35463724]
 [0.07820986 0.14799759 0.33675171 0.59167544 0.56782895 0.3208946 ]]


In [11]:
n=3
p=4
m=5

arr_nxp=np.random.rand(n,p)
print(arr_nxp,"\n")
arr_pxm=np.random.rand(p,m)
print(arr_pxm,"\n")
dotproduct=np.dot(arr_nxp, arr_pxm)
print(dotproduct)

[[0.84036717 0.97705898 0.32158292 0.82742105]
 [0.60552053 0.24996207 0.37168447 0.04095473]
 [0.69633296 0.58452962 0.60189716 0.28522225]] 

[[0.98398134 0.25503335 0.00628122 0.90511274 0.26222562]
 [0.44558647 0.05850142 0.02385521 0.02606258 0.78657748]
 [0.26833451 0.36707204 0.09707809 0.6642501  0.94941417]
 [0.5587388  0.87686025 0.54664169 0.6839612  0.59936928]] 

[[1.81087391 1.11505772 0.51210797 1.56562708 1.79014453]
 [0.82981938 0.34139762 0.06823628 0.82948189 0.73282704]
 [1.26651164 0.68282361 0.2326633  1.24038537 1.38477732]]
